config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "cards#index"

  get :search, to: 'search#search' 

  resources :cards do
    resources :items
         
  end

  get "/help", to: "help#help"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :items
  
  enum category: [:Trip, :Event, :House, :Shoping]
  enum currency: [:UAH, :USD]
  
  validates :title, presence: true, length: { in: 3..128 }
  validates :description, presence: true, length: { in: 5..300 }
  validates :category, inclusion: { in: Card::categories }
  validates :currency, inclusion: { in: Card::currencies }
  
  def total_prices
    items.sum(:price)
  end
end

app/models/concerns/searchable.rb
module Searchable
    extend ActiveSupport::Concern
  
    included do
      include Elasticsearch::Model
      include Elasticsearch::Model::Callbacks
    end
  end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :card
  include Searchable
  
  enum category: [:Traveling, :Clothing, :Taxi, :Cafes, :Shops, :Other].freeze
  
  validates :title, presence: true, length: { in: 3..128 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, inclusion: { in: Item::categories }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cards
  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_card, only: [:show, :edit, :update, :destroy]
  
  def index
    @cards = current_user.cards
  end
  
  def show
    @item = @card.items.build
  end
  
  def new
    @card = collection.build
  end

  def create
    @card = collection.build(card_params)
    flash[:notice] = "Card has been create"

    if @card.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      flash[:notice] = "Card has been updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    flash[:notice] = "Card has been deleted"
    redirect_to root_path
  end

  private

  def collection
    current_user.cards
  end
  
  def find_card
    @card = collection.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:title, :description, :category, :currency)
  end
  
  def item_collection
    find_card.items
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def help
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@card = Card.all
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_card
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @card.items
  end

  def show
  end

  def new
    @item= @card.items.build
  end
  
  def edit; end
    
  def create
    @item = @card.items.build(item_params)
    flash[:notice] = "item has been create"

    if @item.save
      redirect_to(@item.card)
    else
      flash[:error] = @item.errors.full_messages[0]
      render :new
    end
  end  

  def update
    if @item.update(item_params)
      flash[:notice] = "Item has been update"
      redirect_to(@item.card)
    else
      render :edit
    end
  end

  def destroy
    redirect_to @card if @item.destroy
    flash[:notice] = "Item has been deleted"
  end

  private
  
  def find_card
    @card = current_user.cards.find(params[:card_id])
  end

  def find_item
    @item = @card.items.find(params[:id])
  end
  
  def item_params
    params.require(:item).permit(:title, :price, :card_id, :user_id, :category)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        if params[:q].nil?
          @items = []
        else
          @items = Item.search params[:q]
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_name(name)
    case name
    when 'notice' then 'success'
    when 'alert'  then 'danger'
    else name
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cards/_form.html.erb
<div class="card">
  <div class="card-body">
    <section class="card text-center">
       <%=simple_form_for @card do |f| %>
        <div class="card-body form-input mb-3 ">
          <%= f.error_notification %>
          <%= f.input :title, required: true %>
          <%= f.input :description, required: true %>
          <%= f.input :category, as: :radio_buttons, collection: Card::categories.keys %>
          <%= f.input :currency,  as: :radio_buttons, collection: Card::currencies.keys %>
         </div>
        <div class="row mb-3">
          <div class="col-sm-9 offset-sm-3">
            <%= f.button :submit, class: "btn-primary" %>
            <%= link_to "Back", root_path, class: "btn btn-secondary" %>
        </div>
        <%end%>
    </section>
  </div>
</div>

app/views/cards/edit.html.erb
<%= render "shared/header", content: "Edit card"%>
<%= render '/cards/form' %>

app/views/cards/index.html.erb
<div class="container">
  <div class="boards">
    <div class="card">
      <div class="card-body">
        <h2 class='card-title d-flex justify-content-between mb-4'>
          <span>Your cards</span>
          <%= link_to 'New Card', new_card_path, class: 'btn btn-primary' %>
        </h2>
    
        <% @cards.each do |card| %>
          <%= link_to card, class: 'text-decoration-none' do %>
            <div class="card card-card mb-3">
              <div class="card-body">
                <div class="mb-3">
                  <span class="badge badge">
                    <%= card.category %>
                    <%= card.currency %>
                  </span>
                </div>
                <h5 class='card-title text-dark'><b><%= card.title %></b></h5>
                <p class='text-secondary'><%= card.description %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<%= render "shared/header", content: "Create new card"%>
<%= render '/cards/form' %>

app/views/cards/show.html.erb
<div class="container">
  <div class="boards">
    <div class="card">
      <div class="card-body">
        <h2 class='card-title d-flex justify-content-between mb-4'>
          <span><%= @card.title %></span>
          <span><%= @card.currency %></span>
          <span><%= @card.total_prices %></span>
          <p>
            Press <%= link_to 'here', search_path %> to search for items.
          </p>
          <div>
            <%= link_to 'Edit', edit_card_path(@card), class: 'btn btn-outline-primary' %>
            <%= link_to 'Destroy', @card, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' }%>
            <%= link_to "Go back", cards_path, class: "btn btn-outline-dark" %>
          </div>
        </h2>
    
        <div class="mb-4">
          <h6>Add Item</h6>
          <%= form_for([@item.card, @item]) do |f| %>
            <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
    
                <ul>
                <% @item.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <%= f.hidden_field :price %>
            <div class="input-group">
              <%= f.text_field :title, class: 'form-control', placeholder: 'Enter item title...' %>
              <%= f.text_field :price, class: 'form-control', placeholder: 'Enter price...' %>
              <%= f.select :category, Item::categories.keys %>
              <div class="input-group-append">
                <%= f.submit class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
    
        <h4>Items</h4>
        <% @card.items.each do |item| %>
          <% if item.persisted? %>
            <div class="card mb-3">
              <div class="card-body">
                <div class="d-flex justify-content-between">
                  <span class="badge badge-<%= item.price %> mb-3"><%= item.created_at %></span>
                  <div>
                    <%= link_to 'Edit', edit_card_item_path(item.card, item), class: 'btn btn-outline-primary btn-sm' %>
                    <%= link_to 'Destroy', [item.card, item], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
                  </div>
                </div>
                <h5 class='card-title mb-2'>
                  <span><%= item.title %></span>
                </h5>
                <p><%= item.price %></p>
                <p><%= item.category %></p>
              </div>
            </div>
          <% end %>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/help/help.html.erb
<div class="help">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Let's get you</br> some help!</h1>
        <h6>Have any issues? Please send us an <a href="mailto:lyuba@example.com">email.</a></h6>
          <div class="img-wrapper">
            <img src="https://i.ibb.co/bWfN3Qy/undraw-onboarding-o8mv-1.png" alt="undraw-onboarding-o8mv-1" border="0">
          </div>
      </div>
      
      <div class="col-md-6">
        <form>
          <div class="form-group">
            <label for="list">What problem do you have?</label>
            <input type="text" class="form-control" id="list" aria-describedby="emailHelp">
          </div>
          <div class="form-group">
            <label for="tags">Please Few Primary Tags ?</label>
            <input type="text" class="form-control" id="tags">
          </div>
              
          <div class="form-group">
            <label for="describe">Please describe your list of needs?</label>
            <textarea type="text" class="form-control" id="describe" rows="4"></textarea>
          </div>
                
    <button type="button" class="btn btn-primary"><span>Submit</span></button>
    <%= link_to "Back", root_path, class: "btn btn-outline-dark" %>
      </div>
        
      </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render "shared/header", content: "Home"%>
<h3>
  Welcome,
  <% if current_user %>
    <%= current_user.email %>
  <% else %>
    Guest
  <% end %>
</h3>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/_form.html.erb
<section class="shadow-lg mt-5 pb-3 text-dark fs-5">
   <%=simple_form_for [@card, @item] do |f| %>
    <div class="card-body form-input mb-3 ">
      <%= f.error_notification %>
      <%= f.input :title, required: true %>
      <%= f.input :price, required: true %>
      <%= f.input :category, as: :radio_buttons, collection: Item::categories.keys %>
     </div>
    <div class="row mb-3">
      <div class="col-sm-9 offset-sm-3">
        <%= f.button :submit, class: "btn-primary" %>
        <%= link_to "Back", root_path, class: "btn btn-secondary" %>
    </div>
    <%end%>
</section>

app/views/items/edit.html.erb
<%= render "shared/header", content: "Edit Item"%>
<%= render '/items/form' %>

app/views/items/new.html.erb
<%= render "shared/header", content: "Create new Item"%>
<%= render '/items/form' %>

app/views/items/show.html.erb
<div class="container my-5">
  <div class="card bg-light shadow p-3 mb-5 rounded fs-5">
    <div class="row">
      <div class="col">
        <h2 class="text-center">
          <%= @item.title%>
        </h2>
      </div>
    </div>
    <div class="row my-1">
      <div class="col-sm-2">
        Amout
      </div>
      <div class="col-sm-10">
        <%= @item.price || '---' %>
      </div>
    </div>
    <div class="row my-1">
      <div class="col-sm-2">
        Category
      </div>
      <div class="col-sm-10">
        <%= @item.category %>
      </div>
    </div>
    <div class="row my-1">
      <div class="col-sm-2">
        Create date
      </div>
      <div class="col-sm-10">
        <div class="text-center">
         <%= @item.created_at %>
        </div>
      </div>
    </div>
    <div class="border-bottom pb-2">
      <%= link_to "Back", @root_path, class: "btn btn-outline-light" %>
      <%= link_to "Edit", edit_card_item_path(@card), class: "btn btn-outline-warning mx-2" %>
      <%= link_to "Remove", card_item_path(@card), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FTLTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    
    <%=render 'shared/navbar' %>
    <%=render 'shared/alert' %>  
    <%= yield %>
    <%=render 'shared/footer' %>  
  </body>
</html>

app/views/search/search.html.erb
<h1>Items Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
<ul>
  <% @items.each do |item| %>
    <li>
      <h3>
        <%= link_to item.title, controller: "cards", action: "show", id: item._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/shared/_alert.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= flash_class_name(name) %>" role="alert">
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer"> 
  <p>&copy;2021 Lyubov Pidoshva | All Rights Reserved :)</p>
  <%=render 'shared/share' %>
</footer>

app/views/shared/_header.html.erb
<div class="header">
  <h2 class="text-center">
    <%= content %>
  </h2>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to "FTLTask", root_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to "FTLTask", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person" style="font-size: 2rem; color: #f8f9fa;"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "My settings", "#", class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Help", '/help', class: "dropdown-item"  %>
                </li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            </li>
          </li>
        <% else %>
          </li>
            <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link active" %>
          </li>
          </li>
            <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_share.html.erb
<a class="btn btn-primary" type="button" role="button" title="Share on twitter"
  href="https://twitter.com/intent/tweet?text=“<%= "FTLTask App please registrations" %>”&url=<%= new_user_registration_url %>&via=twitter" rel="noopener">
  <i class="bi bi-twitter me-2"></i>
  Twitter
</a>
<a class="btn btn-primary" type="button" role="button" title="Share on facebook"
  href="#">
  <i class="bi bi-facebook"></i>
  Facebook
</a>
<a class="btn btn-primary" type="button" role="button" title="Share on linkedin"
  href="#" rel="noopener">
  <i class="bi bi-linkedin"></i>
  Linkedin
</a>